import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import ThemeProvider from "@/providers/ThemeProvider";
import UserProvider from "@/providers/UserProvider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import {Card, CardContent, CardHeader} from "@/components/ui/card";
import {Avatar} from "@/components/ui/avatar";
import {Badge} from "@/components/ui/badge";

import './globals.scss';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Blog about frontend development',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {


    return (
        <html lang="ru">
        <head>
            <meta name="yandex-verification" content="9d268429e709cc18" />
            <link rel="icon" href="/favicon.png" sizes="32x32" type="image/png"/>
        </head>
        <ThemeProvider>
            <UserProvider>
                <body className={inter.className + "lap:min-h-screen bg-gray-800 dark:bg-gray-800"}>
                <Header/>
                <main
                    className="flex lap:flex-row mob:flex-col mob:mt-14 justify-between px-4 py-6 md:px-6 md:py-12 lg:py-16 mob:p-2">
                    <div className="lap:w-1/12 lap:block mob:hidden"></div>
                    <section className="lap:w-3/5 mob:w-full space-y-4">{children}</section>
                    <aside className="lap:w-80 space-y-4 px-2 mob:hidden lap:block">
                        <Card className="w-full">
                            <CardHeader>
                                <h2 className="text-xl font-bold">About Me</h2>
                            </CardHeader>
                            <CardContent className="flex flex-col gap-4">
                                <Avatar/>
                                <p>Hi, I m a frontend developer. This is my blog where I write about various topics that
                                    interest me.</p>
                            </CardContent>
                        </Card>
                        <Card>
                            <CardHeader>
                                <h2 className="text-xl font-bold">Categories</h2>
                            </CardHeader>
                            <CardContent>
                                <Badge>Next.js</Badge>
                                <Badge>React</Badge>
                            </CardContent>
                        </Card>
                    </aside>
                </main>
                <Footer/>
                </body>
            </UserProvider>
        </ThemeProvider>
        </html>
    )
};
