import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link";
import ThemeProvider from "@/providers/ThemeProvider";
import {ToggleTheme} from "@/components/toggle-theme";

import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>
          <div className="min-h-screen bg-gray-100 dark:bg-gray-800">
            <header className="flex h-20 w-full shrink-0 items-center px-4 md:px-6 gap-4">
              <Link href="#">
                <h1 className="font-bold text-4xl">My Blog</h1>
              </Link>
              <Link href="/">Home</Link>
              <Link href="aboutPage">About</Link>
              <ToggleTheme/>
            </header>
            {children}
            <footer className="flex h-20 w-full shrink-0 items-center px-4 md:px-6">
              <Link href="#">
                <h2 className="font-semibold text-lg">© 2023 My Blog</h2>
              </Link>
            </footer>
          </div>
        </body>
      </ThemeProvider>
    </html>
  )
}
